# coding: utf-8

"""
    Stripy Horse API

    Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from stripyhorse.models.preflight_input_body import PreflightInputBody

class TestPreflightInputBody(unittest.TestCase):
    """PreflightInputBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PreflightInputBody:
        """Test PreflightInputBody
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PreflightInputBody`
        """
        model = PreflightInputBody()
        if include_optional:
            return PreflightInputBody(
                dpmm = 6,
                height_mm = 0,
                preset = '4x6',
                width_mm = 0,
                zpl = ''
            )
        else:
            return PreflightInputBody(
                zpl = '',
        )
        """

    def testPreflightInputBody(self):
        """Test PreflightInputBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
