# coding: utf-8

"""
    Stripy Horse API

    Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from stripyhorse.api.compose_api import ComposeApi


class TestComposeApi(unittest.TestCase):
    """ComposeApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ComposeApi()

    def tearDown(self) -> None:
        pass

    def test_compose_label(self) -> None:
        """Test case for compose_label

        Compose ZPL from typed JSON elements
        """
        pass


if __name__ == '__main__':
    unittest.main()
