# coding: utf-8

"""
    Stripy Horse API

    Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from stripyhorse.models.preflight_output_body import PreflightOutputBody

class TestPreflightOutputBody(unittest.TestCase):
    """PreflightOutputBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PreflightOutputBody:
        """Test PreflightOutputBody
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PreflightOutputBody`
        """
        model = PreflightOutputBody()
        if include_optional:
            return PreflightOutputBody(
                labels = [
                    stripyhorse.models.report.Report(
                        barcodes = [
                            stripyhorse.models.barcode.Barcode(
                                blur_margin_dots = 56, 
                                checks = [
                                    stripyhorse.models.check.Check(
                                        detail = '', 
                                        name = '', 
                                        status = 'pass', )
                                    ], 
                                cross_dpi = [
                                    stripyhorse.models.dpi_verdict.DPIVerdict(
                                        dpmm = 56, 
                                        ok = True, 
                                        x_dimension_mm = 1.337, )
                                    ], 
                                format = '', 
                                module_dots = 1.337, 
                                quiet_left_modules = 1.337, 
                                quiet_right_modules = 1.337, 
                                value = '', 
                                x_dimension_mm = 1.337, )
                            ], 
                        grade = 'pass', 
                        warnings = [
                            ''
                            ], )
                    ],
                lint = [
                    stripyhorse.models.finding.Finding(
                        code = '', 
                        label = 56, 
                        message = '', 
                        severity = 'error', )
                    ]
            )
        else:
            return PreflightOutputBody(
                labels = [
                    stripyhorse.models.report.Report(
                        barcodes = [
                            stripyhorse.models.barcode.Barcode(
                                blur_margin_dots = 56, 
                                checks = [
                                    stripyhorse.models.check.Check(
                                        detail = '', 
                                        name = '', 
                                        status = 'pass', )
                                    ], 
                                cross_dpi = [
                                    stripyhorse.models.dpi_verdict.DPIVerdict(
                                        dpmm = 56, 
                                        ok = True, 
                                        x_dimension_mm = 1.337, )
                                    ], 
                                format = '', 
                                module_dots = 1.337, 
                                quiet_left_modules = 1.337, 
                                quiet_right_modules = 1.337, 
                                value = '', 
                                x_dimension_mm = 1.337, )
                            ], 
                        grade = 'pass', 
                        warnings = [
                            ''
                            ], )
                    ],
                lint = [
                    stripyhorse.models.finding.Finding(
                        code = '', 
                        label = 56, 
                        message = '', 
                        severity = 'error', )
                    ],
        )
        """

    def testPreflightOutputBody(self):
        """Test PreflightOutputBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
