# coding: utf-8

"""
    Stripy Horse API

    Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from stripyhorse.api.printers_api import PrintersApi


class TestPrintersApi(unittest.TestCase):
    """PrintersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PrintersApi()

    def tearDown(self) -> None:
        pass

    def test_parse_host_status(self) -> None:
        """Test case for parse_host_status

        Decode a Zebra ~HS host status response
        """
        pass


if __name__ == '__main__':
    unittest.main()
