# coding: utf-8

"""
    Stripy Horse API

    Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from stripyhorse.models.element import Element

class TestElement(unittest.TestCase):
    """Element unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Element:
        """Test Element
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Element`
        """
        model = Element()
        if include_optional:
            return Element(
                align = '',
                anchor = '',
                columns = 0,
                corner_radius = 0,
                data = '',
                diameter = 56,
                error_correction = '',
                font = '',
                font_height = 56,
                font_width = 56,
                height = 56,
                length = 56,
                line_spacing = 56,
                lines = 56,
                magnification = 56,
                max_width = 56,
                mode = '',
                module_size = 56,
                module_width = 56,
                orientation = '',
                png = '',
                print_text = True,
                rotation = 0,
                rows = 0,
                text = '',
                thickness = 56,
                threshold = 0,
                type = 'text',
                width = 56,
                x = 0,
                y = 0,
                zpl = ''
            )
        else:
            return Element(
                type = 'text',
        )
        """

    def testElement(self):
        """Test Element"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
