# coding: utf-8

"""
    Stripy Horse API

    Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.

    The version of the OpenAPI document: 1.0.0
    Contact: ben@stripyhorse.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from stripyhorse.models.unicode_output_body import UnicodeOutputBody

class TestUnicodeOutputBody(unittest.TestCase):
    """UnicodeOutputBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UnicodeOutputBody:
        """Test UnicodeOutputBody
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UnicodeOutputBody`
        """
        model = UnicodeOutputBody()
        if include_optional:
            return UnicodeOutputBody(
                fields_rasterized = 56,
                skipped = [
                    ''
                    ],
                zpl = ''
            )
        else:
            return UnicodeOutputBody(
                fields_rasterized = 56,
                zpl = '',
        )
        """

    def testUnicodeOutputBody(self):
        """Test UnicodeOutputBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
