# coding: utf-8

"""
    Stripy Horse API

    Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from stripyhorse.models.report import Report

class TestReport(unittest.TestCase):
    """Report unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Report:
        """Test Report
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Report`
        """
        model = Report()
        if include_optional:
            return Report(
                barcodes = [
                    stripyhorse.models.barcode.Barcode(
                        blur_margin_dots = 56, 
                        checks = [
                            stripyhorse.models.check.Check(
                                detail = '', 
                                name = '', 
                                status = 'pass', )
                            ], 
                        cross_dpi = [
                            stripyhorse.models.dpi_verdict.DPIVerdict(
                                dpmm = 56, 
                                ok = True, 
                                x_dimension_mm = 1.337, )
                            ], 
                        format = '', 
                        module_dots = 1.337, 
                        quiet_left_modules = 1.337, 
                        quiet_right_modules = 1.337, 
                        value = '', 
                        x_dimension_mm = 1.337, )
                    ],
                grade = 'pass',
                warnings = [
                    ''
                    ]
            )
        else:
            return Report(
                barcodes = [
                    stripyhorse.models.barcode.Barcode(
                        blur_margin_dots = 56, 
                        checks = [
                            stripyhorse.models.check.Check(
                                detail = '', 
                                name = '', 
                                status = 'pass', )
                            ], 
                        cross_dpi = [
                            stripyhorse.models.dpi_verdict.DPIVerdict(
                                dpmm = 56, 
                                ok = True, 
                                x_dimension_mm = 1.337, )
                            ], 
                        format = '', 
                        module_dots = 1.337, 
                        quiet_left_modules = 1.337, 
                        quiet_right_modules = 1.337, 
                        value = '', 
                        x_dimension_mm = 1.337, )
                    ],
                grade = 'pass',
        )
        """

    def testReport(self):
        """Test Report"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
