# coding: utf-8

"""
    Stripy Horse API

    Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from stripyhorse.models.host_status_output_body import HostStatusOutputBody

class TestHostStatusOutputBody(unittest.TestCase):
    """HostStatusOutputBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HostStatusOutputBody:
        """Test HostStatusOutputBody
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HostStatusOutputBody`
        """
        model = HostStatusOutputBody()
        if include_optional:
            return HostStatusOutputBody(
                fields = [
                    stripyhorse.models.status_field.StatusField(
                        field = '', 
                        raw = '', 
                        value = '', )
                    ],
                status = stripyhorse.models.host_status.HostStatus(
                    blocking = True, 
                    buffer_full = True, 
                    comm_settings = '', 
                    corrupt_ram = True, 
                    diagnostic_mode = True, 
                    formats_in_buffer = 56, 
                    function_settings = '', 
                    graphics_stored = 56, 
                    head_up = True, 
                    label_length_dots = 56, 
                    labels_remaining = 56, 
                    over_temp = True, 
                    paper_out = True, 
                    partial_format = True, 
                    password = '', 
                    paused = True, 
                    print_mode = '', 
                    ribbon_out = True, 
                    static_ram = True, 
                    thermal_transfer = True, 
                    under_temp = True, )
            )
        else:
            return HostStatusOutputBody(
                fields = [
                    stripyhorse.models.status_field.StatusField(
                        field = '', 
                        raw = '', 
                        value = '', )
                    ],
                status = stripyhorse.models.host_status.HostStatus(
                    blocking = True, 
                    buffer_full = True, 
                    comm_settings = '', 
                    corrupt_ram = True, 
                    diagnostic_mode = True, 
                    formats_in_buffer = 56, 
                    function_settings = '', 
                    graphics_stored = 56, 
                    head_up = True, 
                    label_length_dots = 56, 
                    labels_remaining = 56, 
                    over_temp = True, 
                    paper_out = True, 
                    partial_format = True, 
                    password = '', 
                    paused = True, 
                    print_mode = '', 
                    ribbon_out = True, 
                    static_ram = True, 
                    thermal_transfer = True, 
                    under_temp = True, ),
        )
        """

    def testHostStatusOutputBody(self):
        """Test HostStatusOutputBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
