# coding: utf-8

"""
    Stripy Horse API

    Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from stripyhorse.models.list_printers_output_body import ListPrintersOutputBody

class TestListPrintersOutputBody(unittest.TestCase):
    """ListPrintersOutputBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListPrintersOutputBody:
        """Test ListPrintersOutputBody
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListPrintersOutputBody`
        """
        model = ListPrintersOutputBody()
        if include_optional:
            return ListPrintersOutputBody(
                printers = [
                    stripyhorse.models.printer_body.PrinterBody(
                        anonymize = True, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        dpmm = 56, 
                        expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        height_mm = 1.337, 
                        id = '', 
                        ingest_url = '', 
                        mode = 'ephemeral', 
                        name = '', 
                        state = stripyhorse.models.status_snapshot.StatusSnapshot(
                            darkness = '', 
                            faults = stripyhorse.models.faults.Faults(
                                head_up = True, 
                                over_temp = True, 
                                paper_out = True, 
                                paused = True, 
                                ribbon_out = True, 
                                under_temp = True, ), 
                            formats_in_buffer = 56, 
                            friendly_name = '', 
                            label_length_dots = 56, 
                            odometer = 56, 
                            queue = [
                                stripyhorse.models.held_job.HeldJob(
                                    bytes = 56, 
                                    received_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                    source = '', )
                                ], 
                            speed_ips = '', 
                            tear_off = '', 
                            width_dots = 56, ), 
                        tcp = stripyhorse.models.printer_body_tcp_struct.PrinterBodyTCPStruct(
                            host = '', 
                            port = 56, ), 
                        webhook_secret = '', 
                        webhook_url = '', 
                        width_mm = 1.337, )
                    ]
            )
        else:
            return ListPrintersOutputBody(
                printers = [
                    stripyhorse.models.printer_body.PrinterBody(
                        anonymize = True, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        dpmm = 56, 
                        expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        height_mm = 1.337, 
                        id = '', 
                        ingest_url = '', 
                        mode = 'ephemeral', 
                        name = '', 
                        state = stripyhorse.models.status_snapshot.StatusSnapshot(
                            darkness = '', 
                            faults = stripyhorse.models.faults.Faults(
                                head_up = True, 
                                over_temp = True, 
                                paper_out = True, 
                                paused = True, 
                                ribbon_out = True, 
                                under_temp = True, ), 
                            formats_in_buffer = 56, 
                            friendly_name = '', 
                            label_length_dots = 56, 
                            odometer = 56, 
                            queue = [
                                stripyhorse.models.held_job.HeldJob(
                                    bytes = 56, 
                                    received_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                    source = '', )
                                ], 
                            speed_ips = '', 
                            tear_off = '', 
                            width_dots = 56, ), 
                        tcp = stripyhorse.models.printer_body_tcp_struct.PrinterBodyTCPStruct(
                            host = '', 
                            port = 56, ), 
                        webhook_secret = '', 
                        webhook_url = '', 
                        width_mm = 1.337, )
                    ],
        )
        """

    def testListPrintersOutputBody(self):
        """Test ListPrintersOutputBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
