# coding: utf-8

"""
    Stripy Horse API

    Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from stripyhorse.models.status_snapshot import StatusSnapshot

class TestStatusSnapshot(unittest.TestCase):
    """StatusSnapshot unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StatusSnapshot:
        """Test StatusSnapshot
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StatusSnapshot`
        """
        model = StatusSnapshot()
        if include_optional:
            return StatusSnapshot(
                darkness = '',
                faults = stripyhorse.models.faults.Faults(
                    head_up = True, 
                    over_temp = True, 
                    paper_out = True, 
                    paused = True, 
                    ribbon_out = True, 
                    under_temp = True, ),
                formats_in_buffer = 56,
                friendly_name = '',
                label_length_dots = 56,
                odometer = 56,
                speed_ips = '',
                tear_off = '',
                width_dots = 56
            )
        else:
            return StatusSnapshot(
                darkness = '',
                faults = stripyhorse.models.faults.Faults(
                    head_up = True, 
                    over_temp = True, 
                    paper_out = True, 
                    paused = True, 
                    ribbon_out = True, 
                    under_temp = True, ),
                formats_in_buffer = 56,
                friendly_name = '',
                label_length_dots = 56,
                odometer = 56,
                speed_ips = '',
                tear_off = '',
                width_dots = 56,
        )
        """

    def testStatusSnapshot(self):
        """Test StatusSnapshot"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
