# coding: utf-8

"""
    Stripy Horse API

    Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from stripyhorse.api.simulator_api import SimulatorApi


class TestSimulatorApi(unittest.TestCase):
    """SimulatorApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SimulatorApi()

    def tearDown(self) -> None:
        pass

    def test_clear_jobs(self) -> None:
        """Test case for clear_jobs

        Delete all captured jobs
        """
        pass

    def test_create_printer(self) -> None:
        """Test case for create_printer

        Create a virtual printer
        """
        pass

    def test_delete_printer(self) -> None:
        """Test case for delete_printer

        Delete a printer and its captured jobs
        """
        pass

    def test_get_job(self) -> None:
        """Test case for get_job

        Get one job including its raw ZPL
        """
        pass

    def test_get_job_label(self) -> None:
        """Test case for get_job_label

        Get one rendered label as a PNG
        """
        pass

    def test_get_printer(self) -> None:
        """Test case for get_printer

        Get a printer with live state
        """
        pass

    def test_list_jobs(self) -> None:
        """Test case for list_jobs

        List captured jobs, newest first
        """
        pass

    def test_list_printers(self) -> None:
        """Test case for list_printers

        List your printers
        """
        pass

    def test_reset_printer(self) -> None:
        """Test case for reset_printer

        Clear all faults and flush held jobs
        """
        pass

    def test_set_printer_faults(self) -> None:
        """Test case for set_printer_faults

        Inject or clear fault conditions
        """
        pass

    def test_update_printer(self) -> None:
        """Test case for update_printer

        Rename a printer or set its webhook URL
        """
        pass


if __name__ == '__main__':
    unittest.main()
