# coding: utf-8

"""
    Stripy Horse API

    Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from stripyhorse.models.convert_output_body import ConvertOutputBody

class TestConvertOutputBody(unittest.TestCase):
    """ConvertOutputBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConvertOutputBody:
        """Test ConvertOutputBody
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConvertOutputBody`
        """
        model = ConvertOutputBody()
        if include_optional:
            return ConvertOutputBody(
                pages = [
                    stripyhorse.models.converted_page.ConvertedPage(
                        page = 56, 
                        zpl = '', )
                    ]
            )
        else:
            return ConvertOutputBody(
                pages = [
                    stripyhorse.models.converted_page.ConvertedPage(
                        page = 56, 
                        zpl = '', )
                    ],
        )
        """

    def testConvertOutputBody(self):
        """Test ConvertOutputBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
