# coding: utf-8

"""
    Stripy Horse API

    Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from stripyhorse.api.convert_api import ConvertApi


class TestConvertApi(unittest.TestCase):
    """ConvertApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ConvertApi()

    def tearDown(self) -> None:
        pass

    def test_convert_batch(self) -> None:
        """Test case for convert_batch

        Convert many documents in one request, results streamed
        """
        pass

    def test_convert_document(self) -> None:
        """Test case for convert_document

        Convert a PDF or image to ZPL
        """
        pass

    def test_convert_html(self) -> None:
        """Test case for convert_html

        Convert an HTML label design to ZPL
        """
        pass

    def test_convert_zpl_to_html(self) -> None:
        """Test case for convert_zpl_to_html

        Decompile ZPL into editable HTML
        """
        pass

    def test_rasterize_unicode(self) -> None:
        """Test case for rasterize_unicode

        Make Unicode ZPL printable on any Zebra
        """
        pass

    def test_stamp_zpl(self) -> None:
        """Test case for stamp_zpl

        Stamp an image onto ZPL labels
        """
        pass

    def test_void_zpl(self) -> None:
        """Test case for void_zpl

        Stamp ZPL as void / do-not-ship
        """
        pass


if __name__ == '__main__':
    unittest.main()
