# coding: utf-8

"""
    Stripy Horse API

    Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from stripyhorse.api.render_api import RenderApi


class TestRenderApi(unittest.TestCase):
    """RenderApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RenderApi()

    def tearDown(self) -> None:
        pass

    def test_preflight_label(self) -> None:
        """Test case for preflight_label

        Grade a label's barcodes before they ship
        """
        pass

    def test_render_zpl(self) -> None:
        """Test case for render_zpl

        Render ZPL to PNG images
        """
        pass

    def test_render_zpl_png(self) -> None:
        """Test case for render_zpl_png

        Render ZPL and return the first label as a raw PNG
        """
        pass


if __name__ == '__main__':
    unittest.main()
