# coding: utf-8

"""
    Stripy Horse API

    Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.

    The version of the OpenAPI document: 1.0.0
    Contact: ben@stripyhorse.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from stripyhorse.models.check import Check
from stripyhorse.models.dpi_verdict import DPIVerdict
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Barcode(BaseModel):
    """
    Barcode
    """ # noqa: E501
    blur_margin_dots: StrictInt = Field(description="Largest blur radius the symbol survives; 0 = no margin", alias="blurMarginDots")
    checks: Optional[List[Check]]
    cross_dpi: Optional[List[DPIVerdict]] = Field(default=None, description="X-dimension at other print densities, same dot counts", alias="crossDpi")
    format: StrictStr = Field(description="CODE_128, CODE_39, ITF, QR_CODE, DATA_MATRIX")
    module_dots: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Measured narrow-element width in printer dots (1D only)", alias="moduleDots")
    quiet_left_modules: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="quietLeftModules")
    quiet_right_modules: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="quietRightModules")
    value: StrictStr
    x_dimension_mm: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Physical narrow-element width at the analyzed density", alias="xDimensionMm")
    __properties: ClassVar[List[str]] = ["blurMarginDots", "checks", "crossDpi", "format", "moduleDots", "quietLeftModules", "quietRightModules", "value", "xDimensionMm"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Barcode from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in checks (list)
        _items = []
        if self.checks:
            for _item_checks in self.checks:
                if _item_checks:
                    _items.append(_item_checks.to_dict())
            _dict['checks'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in cross_dpi (list)
        _items = []
        if self.cross_dpi:
            for _item_cross_dpi in self.cross_dpi:
                if _item_cross_dpi:
                    _items.append(_item_cross_dpi.to_dict())
            _dict['crossDpi'] = _items
        # set to None if checks (nullable) is None
        # and model_fields_set contains the field
        if self.checks is None and "checks" in self.model_fields_set:
            _dict['checks'] = None

        # set to None if cross_dpi (nullable) is None
        # and model_fields_set contains the field
        if self.cross_dpi is None and "cross_dpi" in self.model_fields_set:
            _dict['crossDpi'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Barcode from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "blurMarginDots": obj.get("blurMarginDots"),
            "checks": [Check.from_dict(_item) for _item in obj["checks"]] if obj.get("checks") is not None else None,
            "crossDpi": [DPIVerdict.from_dict(_item) for _item in obj["crossDpi"]] if obj.get("crossDpi") is not None else None,
            "format": obj.get("format"),
            "moduleDots": obj.get("moduleDots"),
            "quietLeftModules": obj.get("quietLeftModules"),
            "quietRightModules": obj.get("quietRightModules"),
            "value": obj.get("value"),
            "xDimensionMm": obj.get("xDimensionMm")
        })
        return _obj


