# coding: utf-8

"""
    Stripy Horse API

    Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.

    The version of the OpenAPI document: 1.0.0
    Contact: ben@stripyhorse.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from stripyhorse.models.element import Element
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ComposeInputBody(BaseModel):
    """
    ComposeInputBody
    """ # noqa: E501
    dpmm: Optional[StrictInt] = None
    elements: Optional[List[Element]]
    height_mm: Optional[Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]]] = Field(default=None, alias="heightMm")
    preset: Optional[StrictStr] = Field(default=None, description="Named label size; alternative to widthMm/heightMm")
    preview: Optional[StrictBool] = Field(default=None, description="Also render the composed label to PNG")
    variables: Optional[Dict[str, StrictStr]] = Field(default=None, description="Values for {{name}} references")
    width_mm: Optional[Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]]] = Field(default=None, alias="widthMm")
    __properties: ClassVar[List[str]] = ["dpmm", "elements", "heightMm", "preset", "preview", "variables", "widthMm"]

    @field_validator('dpmm')
    def dpmm_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set([6, 8, 12, 24]):
            raise ValueError("must be one of enum values (6, 8, 12, 24)")
        return value

    @field_validator('preset')
    def preset_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['4x6', '6x4', '4x8', '4x4', '4x3', '3x5', '5x3', '4x2', '2x4', '2x3', '3x2', '2x1', '3x1', '4x1', '2.25x1.25', '1.5x1', '1x1', 'netstamp', 'a6']):
            raise ValueError("must be one of enum values ('4x6', '6x4', '4x8', '4x4', '4x3', '3x5', '5x3', '4x2', '2x4', '2x3', '3x2', '2x1', '3x1', '4x1', '2.25x1.25', '1.5x1', '1x1', 'netstamp', 'a6')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ComposeInputBody from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in elements (list)
        _items = []
        if self.elements:
            for _item_elements in self.elements:
                if _item_elements:
                    _items.append(_item_elements.to_dict())
            _dict['elements'] = _items
        # set to None if elements (nullable) is None
        # and model_fields_set contains the field
        if self.elements is None and "elements" in self.model_fields_set:
            _dict['elements'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ComposeInputBody from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "dpmm": obj.get("dpmm"),
            "elements": [Element.from_dict(_item) for _item in obj["elements"]] if obj.get("elements") is not None else None,
            "heightMm": obj.get("heightMm"),
            "preset": obj.get("preset"),
            "preview": obj.get("preview"),
            "variables": obj.get("variables"),
            "widthMm": obj.get("widthMm")
        })
        return _obj


