# coding: utf-8

"""
    Stripy Horse API

    Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CreatePrinterInputBody(BaseModel):
    """
    CreatePrinterInputBody
    """ # noqa: E501
    anonymize: Optional[StrictBool] = Field(default=None, description="Mask PII and strip graphics from every captured frame")
    dpmm: Optional[StrictInt] = Field(default=None, description="Print density in dots/mm (152/203/300/600 dpi); default 8")
    height_mm: Optional[Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]]] = Field(default=None, alias="heightMm")
    mode: Optional[StrictStr] = None
    name: Annotated[str, Field(min_length=1, strict=True)]
    preset: Optional[StrictStr] = Field(default=None, description="Named label size in inches; alternative to widthMm/heightMm")
    webhook_url: Optional[StrictStr] = Field(default=None, alias="webhookUrl")
    width_mm: Optional[Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]]] = Field(default=None, alias="widthMm")
    __properties: ClassVar[List[str]] = ["anonymize", "dpmm", "heightMm", "mode", "name", "preset", "webhookUrl", "widthMm"]

    @field_validator('dpmm')
    def dpmm_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set([6, 8, 12, 24]):
            raise ValueError("must be one of enum values (6, 8, 12, 24)")
        return value

    @field_validator('mode')
    def mode_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['', 'ephemeral', 'persistent']):
            raise ValueError("must be one of enum values ('', 'ephemeral', 'persistent')")
        return value

    @field_validator('preset')
    def preset_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['4x6', '6x4', '4x4', '4x2', '2x4', '3x5', '5x3', '2x3', '3x2', 'netstamp', '2.25x1.25', '2x1', '3x1', '4x1', '1x1', '4x3', '4x8', 'a6']):
            raise ValueError("must be one of enum values ('4x6', '6x4', '4x4', '4x2', '2x4', '3x5', '5x3', '2x3', '3x2', 'netstamp', '2.25x1.25', '2x1', '3x1', '4x1', '1x1', '4x3', '4x8', 'a6')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreatePrinterInputBody from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreatePrinterInputBody from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "anonymize": obj.get("anonymize"),
            "dpmm": obj.get("dpmm"),
            "heightMm": obj.get("heightMm"),
            "mode": obj.get("mode"),
            "name": obj.get("name"),
            "preset": obj.get("preset"),
            "webhookUrl": obj.get("webhookUrl"),
            "widthMm": obj.get("widthMm")
        })
        return _obj


