# coding: utf-8

"""
    Stripy Horse API

    Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Element(BaseModel):
    """
    Element
    """ # noqa: E501
    align: Optional[StrictStr] = Field(default=None, description="Alignment when wrapping")
    anchor: Optional[StrictStr] = Field(default=None, description="Which corner x,y names. topLeft (^FO, default); bottomLeft (^FT: the text baseline, what most designer-exported ZPL uses); the Right variants make x the field's right edge (ZPL justification 1)")
    columns: Optional[Annotated[int, Field(le=50, strict=True, ge=0)]] = Field(default=None, description="Grid columns (default 1)")
    corner_radius: Optional[Annotated[int, Field(le=8, strict=True, ge=0)]] = Field(default=None, description="Box corner rounding 0-8", alias="cornerRadius")
    data: Optional[StrictStr] = Field(default=None, description="Barcode payload; {{name}} interpolates")
    diameter: Optional[StrictInt] = Field(default=None, description="Circle diameter in dots")
    error_correction: Optional[StrictStr] = Field(default=None, description="QR error correction (default M)", alias="errorCorrection")
    font: Optional[StrictStr] = Field(default=None, description="Printer font: 0 (scalable, default) or A-Z")
    font_height: Optional[StrictInt] = Field(default=None, description="Character height in dots (text)", alias="fontHeight")
    font_width: Optional[StrictInt] = Field(default=None, description="Character width in dots; 0 follows fontHeight", alias="fontWidth")
    height: Optional[StrictInt] = Field(default=None, description="Bar height in dots (1D) / box height in dots (box)")
    length: Optional[StrictInt] = Field(default=None, description="Line length in dots")
    line_spacing: Optional[StrictInt] = Field(default=None, description="Extra dots between wrapped lines", alias="lineSpacing")
    lines: Optional[StrictInt] = Field(default=None, description="Max lines when wrapping (default 1)")
    magnification: Optional[StrictInt] = Field(default=None, description="QR module magnification (default 3)")
    max_width: Optional[StrictInt] = Field(default=None, description="Wrap text into a block this many dots wide", alias="maxWidth")
    mode: Optional[StrictStr] = Field(default=None, description="Code 128 mode: N none (default), U UCC case, A automatic subset switching, D UCC/EAN application identifiers")
    module_size: Optional[StrictInt] = Field(default=None, description="DataMatrix module size in dots (default 4)", alias="moduleSize")
    module_width: Optional[StrictInt] = Field(default=None, description="Narrow element width in dots (1D; default 3)", alias="moduleWidth")
    orientation: Optional[StrictStr] = Field(default=None, description="Line direction")
    png: Optional[StrictStr] = Field(default=None, description="PNG/GIF/JPEG, base64-encoded")
    print_text: Optional[StrictBool] = Field(default=None, description="Print the human-readable line under 1D barcodes (default true)", alias="printText")
    rotation: Optional[StrictInt] = None
    rows: Optional[Annotated[int, Field(le=50, strict=True, ge=0)]] = Field(default=None, description="Grid rows (default 1)")
    text: Optional[StrictStr] = Field(default=None, description="Text content; {{name}} interpolates from variables")
    thickness: Optional[StrictInt] = Field(default=None, description="Stroke thickness in dots (default 1)")
    threshold: Optional[Annotated[int, Field(le=255, strict=True, ge=0)]] = Field(default=None, description="Bitonal threshold (default 128)")
    type: StrictStr = Field(description="What to place")
    width: Optional[StrictInt] = Field(default=None, description="Box/image width in dots")
    x: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Left edge in dots")
    y: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Top edge in dots")
    zpl: Optional[StrictStr] = Field(default=None, description="Verbatim ZPL commands (raw only) - the escape hatch")
    __properties: ClassVar[List[str]] = ["align", "anchor", "columns", "cornerRadius", "data", "diameter", "errorCorrection", "font", "fontHeight", "fontWidth", "height", "length", "lineSpacing", "lines", "magnification", "maxWidth", "mode", "moduleSize", "moduleWidth", "orientation", "png", "printText", "rotation", "rows", "text", "thickness", "threshold", "type", "width", "x", "y", "zpl"]

    @field_validator('align')
    def align_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['', 'left', 'center', 'right', 'justify']):
            raise ValueError("must be one of enum values ('', 'left', 'center', 'right', 'justify')")
        return value

    @field_validator('anchor')
    def anchor_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['', 'topLeft', 'bottomLeft', 'topRight', 'bottomRight']):
            raise ValueError("must be one of enum values ('', 'topLeft', 'bottomLeft', 'topRight', 'bottomRight')")
        return value

    @field_validator('error_correction')
    def error_correction_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['', 'L', 'M', 'Q', 'H']):
            raise ValueError("must be one of enum values ('', 'L', 'M', 'Q', 'H')")
        return value

    @field_validator('mode')
    def mode_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['', 'N', 'U', 'A', 'D']):
            raise ValueError("must be one of enum values ('', 'N', 'U', 'A', 'D')")
        return value

    @field_validator('orientation')
    def orientation_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['', 'h', 'v']):
            raise ValueError("must be one of enum values ('', 'h', 'v')")
        return value

    @field_validator('rotation')
    def rotation_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set([0, 90, 180, 270]):
            raise ValueError("must be one of enum values (0, 90, 180, 270)")
        return value

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['text', 'barcode128', 'barcode39', 'qr', 'datamatrix', 'box', 'line', 'circle', 'grid', 'image', 'raw']):
            raise ValueError("must be one of enum values ('text', 'barcode128', 'barcode39', 'qr', 'datamatrix', 'box', 'line', 'circle', 'grid', 'image', 'raw')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Element from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Element from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "align": obj.get("align"),
            "anchor": obj.get("anchor"),
            "columns": obj.get("columns"),
            "cornerRadius": obj.get("cornerRadius"),
            "data": obj.get("data"),
            "diameter": obj.get("diameter"),
            "errorCorrection": obj.get("errorCorrection"),
            "font": obj.get("font"),
            "fontHeight": obj.get("fontHeight"),
            "fontWidth": obj.get("fontWidth"),
            "height": obj.get("height"),
            "length": obj.get("length"),
            "lineSpacing": obj.get("lineSpacing"),
            "lines": obj.get("lines"),
            "magnification": obj.get("magnification"),
            "maxWidth": obj.get("maxWidth"),
            "mode": obj.get("mode"),
            "moduleSize": obj.get("moduleSize"),
            "moduleWidth": obj.get("moduleWidth"),
            "orientation": obj.get("orientation"),
            "png": obj.get("png"),
            "printText": obj.get("printText"),
            "rotation": obj.get("rotation"),
            "rows": obj.get("rows"),
            "text": obj.get("text"),
            "thickness": obj.get("thickness"),
            "threshold": obj.get("threshold"),
            "type": obj.get("type"),
            "width": obj.get("width"),
            "x": obj.get("x"),
            "y": obj.get("y"),
            "zpl": obj.get("zpl")
        })
        return _obj


