# coding: utf-8

"""
    Stripy Horse API

    Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.

    The version of the OpenAPI document: 1.0.0
    Contact: ben@stripyhorse.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class HostStatus(BaseModel):
    """
    HostStatus
    """ # noqa: E501
    blocking: StrictBool = Field(description="True when any condition stops printing")
    buffer_full: StrictBool = Field(alias="bufferFull")
    comm_settings: StrictStr = Field(description="Raw communication-settings code", alias="commSettings")
    corrupt_ram: StrictBool = Field(alias="corruptRam")
    diagnostic_mode: StrictBool = Field(alias="diagnosticMode")
    formats_in_buffer: StrictInt = Field(description="Jobs waiting in the receive buffer", alias="formatsInBuffer")
    function_settings: StrictStr = Field(description="Raw function-settings code", alias="functionSettings")
    graphics_stored: StrictInt = Field(alias="graphicsStored")
    head_up: StrictBool = Field(alias="headUp")
    label_length_dots: StrictInt = Field(alias="labelLengthDots")
    labels_remaining: StrictInt = Field(alias="labelsRemaining")
    over_temp: StrictBool = Field(alias="overTemp")
    paper_out: StrictBool = Field(alias="paperOut")
    partial_format: StrictBool = Field(alias="partialFormat")
    password: StrictStr
    paused: StrictBool
    print_mode: StrictStr = Field(description="rewind, peel-off, tear-off, cutter or applicator", alias="printMode")
    ribbon_out: StrictBool = Field(alias="ribbonOut")
    static_ram: StrictBool = Field(alias="staticRam")
    thermal_transfer: StrictBool = Field(alias="thermalTransfer")
    under_temp: StrictBool = Field(alias="underTemp")
    __properties: ClassVar[List[str]] = ["blocking", "bufferFull", "commSettings", "corruptRam", "diagnosticMode", "formatsInBuffer", "functionSettings", "graphicsStored", "headUp", "labelLengthDots", "labelsRemaining", "overTemp", "paperOut", "partialFormat", "password", "paused", "printMode", "ribbonOut", "staticRam", "thermalTransfer", "underTemp"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of HostStatus from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of HostStatus from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "blocking": obj.get("blocking"),
            "bufferFull": obj.get("bufferFull"),
            "commSettings": obj.get("commSettings"),
            "corruptRam": obj.get("corruptRam"),
            "diagnosticMode": obj.get("diagnosticMode"),
            "formatsInBuffer": obj.get("formatsInBuffer"),
            "functionSettings": obj.get("functionSettings"),
            "graphicsStored": obj.get("graphicsStored"),
            "headUp": obj.get("headUp"),
            "labelLengthDots": obj.get("labelLengthDots"),
            "labelsRemaining": obj.get("labelsRemaining"),
            "overTemp": obj.get("overTemp"),
            "paperOut": obj.get("paperOut"),
            "partialFormat": obj.get("partialFormat"),
            "password": obj.get("password"),
            "paused": obj.get("paused"),
            "printMode": obj.get("printMode"),
            "ribbonOut": obj.get("ribbonOut"),
            "staticRam": obj.get("staticRam"),
            "thermalTransfer": obj.get("thermalTransfer"),
            "underTemp": obj.get("underTemp")
        })
        return _obj


