# coding: utf-8

"""
    Stripy Horse API

    Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.

    The version of the OpenAPI document: 1.0.0
    Contact: ben@stripyhorse.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from stripyhorse.models.printer_body_tcp_struct import PrinterBodyTCPStruct
from stripyhorse.models.status_snapshot import StatusSnapshot
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PrinterBody(BaseModel):
    """
    PrinterBody
    """ # noqa: E501
    access_mode: StrictStr = Field(description="Who may print to the TCP port: open (anyone), token (the stream must open with ~SH plus the ingest token), ip (only addresses the org has claimed)", alias="accessMode")
    anonymize: StrictBool = Field(description="When true, PII is masked and graphics stripped from every captured frame")
    created_at: datetime = Field(alias="createdAt")
    dpmm: StrictInt
    expires_at: Optional[datetime] = Field(default=None, alias="expiresAt")
    height_mm: Union[StrictFloat, StrictInt] = Field(alias="heightMm")
    id: StrictStr
    ingest_url: Optional[StrictStr] = Field(default=None, description="HTTPS print capability URL. Only returned on creation.", alias="ingestUrl")
    mode: StrictStr
    name: StrictStr
    state: Optional[StatusSnapshot] = None
    tcp: PrinterBodyTCPStruct
    webhook_secret: Optional[StrictStr] = Field(default=None, description="HMAC-SHA256 key for X-Stripy-Horse-Signature. Only returned on creation.", alias="webhookSecret")
    webhook_url: Optional[StrictStr] = Field(default=None, alias="webhookUrl")
    width_mm: Union[StrictFloat, StrictInt] = Field(alias="widthMm")
    __properties: ClassVar[List[str]] = ["accessMode", "anonymize", "createdAt", "dpmm", "expiresAt", "heightMm", "id", "ingestUrl", "mode", "name", "state", "tcp", "webhookSecret", "webhookUrl", "widthMm"]

    @field_validator('mode')
    def mode_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['ephemeral', 'persistent']):
            raise ValueError("must be one of enum values ('ephemeral', 'persistent')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PrinterBody from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of state
        if self.state:
            _dict['state'] = self.state.to_dict()
        # override the default output from pydantic by calling `to_dict()` of tcp
        if self.tcp:
            _dict['tcp'] = self.tcp.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PrinterBody from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "accessMode": obj.get("accessMode"),
            "anonymize": obj.get("anonymize"),
            "createdAt": obj.get("createdAt"),
            "dpmm": obj.get("dpmm"),
            "expiresAt": obj.get("expiresAt"),
            "heightMm": obj.get("heightMm"),
            "id": obj.get("id"),
            "ingestUrl": obj.get("ingestUrl"),
            "mode": obj.get("mode"),
            "name": obj.get("name"),
            "state": StatusSnapshot.from_dict(obj["state"]) if obj.get("state") is not None else None,
            "tcp": PrinterBodyTCPStruct.from_dict(obj["tcp"]) if obj.get("tcp") is not None else None,
            "webhookSecret": obj.get("webhookSecret"),
            "webhookUrl": obj.get("webhookUrl"),
            "widthMm": obj.get("widthMm")
        })
        return _obj


