# coding: utf-8

"""
    Stripy Horse API

    Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from stripyhorse.models.barcode import Barcode
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Report(BaseModel):
    """
    Report
    """ # noqa: E501
    barcodes: Optional[List[Barcode]]
    grade: StrictStr = Field(description="Worst status across all checks")
    warnings: Optional[List[StrictStr]] = Field(default=None, description="Label-level notes, e.g. no barcodes found")
    __properties: ClassVar[List[str]] = ["barcodes", "grade", "warnings"]

    @field_validator('grade')
    def grade_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['pass', 'warn', 'fail']):
            raise ValueError("must be one of enum values ('pass', 'warn', 'fail')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Report from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in barcodes (list)
        _items = []
        if self.barcodes:
            for _item_barcodes in self.barcodes:
                if _item_barcodes:
                    _items.append(_item_barcodes.to_dict())
            _dict['barcodes'] = _items
        # set to None if barcodes (nullable) is None
        # and model_fields_set contains the field
        if self.barcodes is None and "barcodes" in self.model_fields_set:
            _dict['barcodes'] = None

        # set to None if warnings (nullable) is None
        # and model_fields_set contains the field
        if self.warnings is None and "warnings" in self.model_fields_set:
            _dict['warnings'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Report from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "barcodes": [Barcode.from_dict(_item) for _item in obj["barcodes"]] if obj.get("barcodes") is not None else None,
            "grade": obj.get("grade"),
            "warnings": obj.get("warnings")
        })
        return _obj


