# coding: utf-8

"""
    Stripy Horse API

    Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List
from stripyhorse.models.faults import Faults
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class StatusSnapshot(BaseModel):
    """
    StatusSnapshot
    """ # noqa: E501
    darkness: StrictStr = Field(description="print.tone setting, e.g. 20.0")
    faults: Faults
    formats_in_buffer: StrictInt = Field(alias="formatsInBuffer")
    friendly_name: StrictStr = Field(description="device.friendly_name override; empty means unset", alias="friendlyName")
    label_length_dots: StrictInt = Field(alias="labelLengthDots")
    odometer: StrictInt
    speed_ips: StrictStr = Field(description="media.speed setting, inches/second", alias="speedIps")
    width_dots: StrictInt = Field(alias="widthDots")
    __properties: ClassVar[List[str]] = ["darkness", "faults", "formatsInBuffer", "friendlyName", "labelLengthDots", "odometer", "speedIps", "widthDots"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StatusSnapshot from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of faults
        if self.faults:
            _dict['faults'] = self.faults.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StatusSnapshot from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "darkness": obj.get("darkness"),
            "faults": Faults.from_dict(obj["faults"]) if obj.get("faults") is not None else None,
            "formatsInBuffer": obj.get("formatsInBuffer"),
            "friendlyName": obj.get("friendlyName"),
            "labelLengthDots": obj.get("labelLengthDots"),
            "odometer": obj.get("odometer"),
            "speedIps": obj.get("speedIps"),
            "widthDots": obj.get("widthDots")
        })
        return _obj


