# coding: utf-8

"""
    Stripy Horse API

    Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Supplies(BaseModel):
    """
    Supplies
    """ # noqa: E501
    labels_left: Optional[StrictInt] = Field(default=None, description="Labels left on the roll", alias="labelsLeft")
    labels_loaded: Optional[StrictInt] = Field(default=None, description="Labels the roll held when it was fitted; 0 means an endless roll", alias="labelsLoaded")
    ribbon_mm_left: Optional[StrictInt] = Field(default=None, description="Millimetres of ribbon left", alias="ribbonMmLeft")
    ribbon_mm_loaded: Optional[StrictInt] = Field(default=None, description="Millimetres of ribbon fitted; 0 means endless, which is also what direct thermal looks like", alias="ribbonMmLoaded")
    __properties: ClassVar[List[str]] = ["labelsLeft", "labelsLoaded", "ribbonMmLeft", "ribbonMmLoaded"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Supplies from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Supplies from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "labelsLeft": obj.get("labelsLeft"),
            "labelsLoaded": obj.get("labelsLoaded"),
            "ribbonMmLeft": obj.get("ribbonMmLeft"),
            "ribbonMmLoaded": obj.get("ribbonMmLoaded")
        })
        return _obj


